language: node_js
node_js:
- "node"
before install:
- 
install:
- npm install
script:
- 
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master